name: Demo de CI con tests en Docker
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
  
    permissions:
      checks: write
      pull-requests: write
  
    steps:
    - name: Checkout                   
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    
    - name: Build to tests stage
      uses: docker/build-push-action@v3
      with:
        tags: addertests:latest   
        target: test              
    
    - name: Copy JUnit test file
      run: |
        id=$(docker create addertests:latest)
        docker cp $id:/app/target/nextest/ci/testresults.xml .
        docker rm $id
    
    - name: Publish test results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: testresults.xml
    
    - name: Build final Docker image
      uses: docker/build-push-action@v3
      with:
        tags: adder:latest
        